aws-samples/amazon-dynamodb-labs

.gitignore
config.toml
content/design-patterns/setup/Step4.en.md
content/design-patterns/setup/Step6.en.md

- fixed CUs in one example
- fixed edit URL, so it pulls up a blob

Fix edit URL, minor doc changes

---

.gitignore
config.toml
content/design-patterns/setup/Step4.en.md
content/design-patterns/setup/Step6.en.md

- Typos fixed in markdown files
- When users click edit, they will be taken to the blob view instead of the edit view

Fix typos in CUs, switched to view URL in "Edit this page" hyperlink

---

content/design-patterns/ex6compos/Step1.en.md
content/design-patterns/ex6compos/Step2.en.md
content/design-patterns/ex6compos/Step3.en.md
content/design-patterns/ex6compos/_index.en.md

Applied updates from CL to Exercise 6, except for step 4 which has already been updated by Zach.  Included new screenshot (awsconsole8.png) currently linked to my S3 bucket version as per instructions.

Exercise 6 updates

---

content/reference-materials/_index.en.md
content/scenarios/Bank Payments/_index.en.md
content/scenarios/Bank Payments/references.en.md
content/scenarios/Retail Cart/_index.en.md
content/scenarios/Retail Cart/references.en.md
content/scenarios/_index.en.md

N/A - typos, clarity, and formatting
Edits based on copyedit feedback.

scenario edits based on copyedit feedback

---

content/design-patterns/ex8streams/Step1.en.md
content/design-patterns/ex8streams/Step2.en.md
content/design-patterns/ex8streams/Step3.en.md
content/design-patterns/ex8streams/Step4.en.md
content/design-patterns/ex8streams/Step5.en.md
content/design-patterns/ex8streams/Step6.en.md
content/design-patterns/ex8streams/_index.en.md

Exercise8-copyedits

---

content/design-patterns/ex5sparse/Step2.en.md

Fix a typo

---

scenario-solutions/bank-payments/BankModel.json
scenario-solutions/retail-cart/CartModel.json

*Issue #38*
Additional lines to add **Service** and **Version**

NoSQL Workbench import issue for solution files

---

content/design-patterns/setup/_index.en.md

Minor spelling fix

---

content/design-patterns/ex8streams/Step3.en.md

Tested during the lab today and it works as expected.
Removes a copy and paste action by allowing the shell to do the work.

Remove copy-paste step

---

content/authors.en.md
content/hands-on-labs/explore-cli/_index.en.md

Add new authors and fix a typo in the new labs section 2

Add new authors and fix a typo in the new labs section 2

---

.github/workflows/main.yml

Adding first workflow

---

content/hands-on-labs/explore-cli/cli-scan.en.md
content/hands-on-labs/explore-console/console-scan.en.md

I noticed a spurious character breaking a URL link. Fixed here.

Minor fixes as I walk through the labs

---

content/hands-on-labs/rdbms-migration/_index.en.md
design-patterns/nohup.out

Small typo fix

---

content/hands-on-labs/rdbms-migration/migration-chapter05.en.md

Fix for markdown tables in migration lab

Fix for markdown tables in migration lab

---

content/hands-on-labs/backups/schedule-backup.md

Fixed small typo on schedule-backup

Minor fix: schedule-backup typo

---

content/hands-on-labs/rdbms-migration/migration-chapter00.en.md

The document has typo "Source" and I have corrected the link to relative path for deployment.

Updated migration-chapter00.en.md to correct "Explore Source Model link

---

content/hands-on-labs/rdbms-migration/migration-chapter03.en.md
static/files/hands-on-labs/migration-env-setup.yaml

The EC2 instance in the hands on labs DMS section fails to configure. This change from Olivier fixes it.

RDBSM Migration template: oro's changes to fix broken template

---

content/event-driven-architecture/ex4summary/Step1.en.md

Modified IAM policy for ReduceLambdaPolicy on solutions page to use wildcards for region and accountID.

ReduceLambdaPolicy in Solutions region and AccountID agnostic

---

content/game-player-data/open-games/Step2.en.md
content/game-player-data/past-games/Step1.en.md
content/game-player-data/setup/Step1.en.md

LGME updates

---

content/hands-on-labs/explore-cli/cli-gsi.en.md
content/hands-on-labs/explore-console/console-read-item-collection.en.md

*Issue #, if available:* In GSI, there is a typo
*Description of changes:* I just add an 'i' in operation

fix(docs): minor changes around typo and space

---

content/hands-on-labs/backups/schedule-backup.md
content/hands-on-labs/explore-cli/cli-read-data.en.md
content/hands-on-labs/explore-console/console-read-data.en.md
content/hands-on-labs/explore-console/console-writing-data.en.md
content/hands-on-labs/rdbms-migration/migration-chapter02-1.en.md
content/hands-on-labs/rdbms-migration/migration-chapter05.en.md
content/hands-on-labs/setup/create-tables.en.md

LHOL Misc updates

---

.gitmodules

remove hugo

---

content/hands-on-labs/rdbms-migration/migration-chapter00.en.md
content/hands-on-labs/rdbms-migration/migration-chapter03.en.md

@amdhing - pulling your changes from the private repo to the public repo. Lab guide changes are done on the public package and then synced to the private repo. In the future, make the change here, then write a basic rsync command to overwrite the content folder of the private repo with the tip of master.

Pulling upstream changes

---

content/hands-on-labs/explore-cli/cli-read-item-collection.en.md

Clarified the documentation location and relevant CLI options

Update docs link

---

content/change-data-capture/ex2/configure-lambda.en.md
content/change-data-capture/ex2/enable-kds-streams.en.md
content/change-data-capture/ex2/index.en.md

Issues pointed out during session which were quick to address

Fixing typos on LCDC Lab

---

content/hands-on-labs/backups/index.en.md
content/hands-on-labs/explore-console/console-read-item-collection.en.md
content/hands-on-labs/explore-console/console-writing-data.en.md
content/hands-on-labs/rdbms-migration/migration-chapter02.en.md
content/hands-on-labs/rdbms-migration/migration-chapter03.en.md

Corrected various errors in the text, typos, and, style/grammar issues.

corrected wording errors and style
